# Generated by Django 5.1 on 2024-09-06 14:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razao_social', models.CharField(max_length=100)),
                ('nome_fantasia', models.CharField(max_length=100)),
                ('cnpj', models.CharField(max_length=15)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rua', models.CharField(max_length=100)),
                ('numero', models.CharField(max_length=10)),
                ('bairro', models.CharField(max_length=50)),
                ('cidade', models.CharField(max_length=50)),
                ('estado', models.CharField(max_length=20)),
                ('pais', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_organizador', models.CharField(max_length=50)),
                ('telefone', models.CharField(max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_evento', models.DateTimeField(default=django.utils.timezone.now)),
                ('tipo_evento', models.CharField(choices=[('C', 'Doação de Comida'), ('R', 'Doação de Roupas'), ('P', 'Doação de Pets+'), ('E', 'Evento Assistencial'), ('O', 'Outros')], max_length=1)),
                ('local_evento', models.CharField(max_length=50)),
                ('limite_evento', models.CharField(max_length=5)),
                ('nome_evento', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('primeiro_nome', models.CharField(max_length=50)),
                ('ultimo_nome', models.CharField(blank=True, max_length=50)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(choices=[('F', 'Feminino'), ('M', 'Masculino'), ('L', 'LGBTQIA+'), ('P', 'Prefiro Não Responder')], max_length=1)),
                ('telefone', models.CharField(max_length=50)),
                ('senha', models.CharField(max_length=100)),
                ('imagem_perfil', models.ImageField(blank=True, upload_to='pictures/%Y/%m/')),
            ],
        ),
    ]
