# Generated by Django 5.1 on 2024-09-21 14:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSolidario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='empresa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetoSolidario.empresa'),
        ),
        migrations.AlterField(
            model_name='evento',
            name='local_evento',
            field=models.CharField(max_length=100),
        ),
    ]
