# Generated by Django 5.1 on 2024-09-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSolidario', '0002_evento_empresa_alter_evento_local_evento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='evento',
            name='local_evento',
        ),
        migrations.AddField(
            model_name='evento',
            name='endereco',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetoSolidario.endereco'),
        ),
    ]
