# Generated by Django 5.1 on 2024-09-23 12:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSolidario', '0003_remove_evento_local_evento_evento_endereco'),
    ]

    operations = [
        migrations.CreateModel(
            name='Estado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('sigla', models.CharField(max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='Pais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoSolidario.estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projetoSolidario.pais'),
        ),
    ]
