# Generated by Django 5.1 on 2024-09-23 13:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSolidario', '0004_estado_pais_alter_endereco_estado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endereco',
            name='estado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetoSolidario.estado'),
        ),
        migrations.AlterField(
            model_name='endereco',
            name='pais',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projetoSolidario.pais'),
        ),
    ]
