# Generated by Django 5.1 on 2024-09-19 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSolidario', '0004_remove_usuario_email_remove_usuario_primeiro_nome_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Calendario',
            new_name='Event',
        ),
        migrations.AlterField(
            model_name='usuario',
            name='telefone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
