# Generated by Django 5.1 on 2024-09-23 13:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projetoSolidario', '0005_alter_endereco_estado_alter_endereco_pais'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='pais',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projetoSolidario.pais'),
            preserve_default=False,
        ),
    ]
